trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
- group: 'test-global-vg'
- group: 'test-secrets-vg'

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Azure Learning Sub(d7e3c15f-a785-4ecd-944b-d03698d68b5d)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az acr login -n $(registry) -u $(registry) -p $(acr-password)
        docker build -t $(registry).azurecr.io/catalog.api:$(Build.BuildId) --build-arg SERVICE=Catalog.API -f Dockerfile .
        docker push $(registry).azurecr.io/catalog.api:$(Build.BuildId)

        az containerapp up \
        -n $(caName) -g $(rg) \
        --environment $(acaEnv) \
        --image $(registry).azurecr.io/catalog.api:$(Build.BuildId) \
        --registry-server '$(registry).azurecr.io'