trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  projectPath: src/Catalog.API
  caName: catalog-test
  rg: testapp-rg
  acaEnv: testappenv12
  registry: eshoptestacr1

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      useGlobalJson: true
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '$(projectPath)'
      feedsToUse: 'config'
      nugetConfigPath: 'nuget.config'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '$(projectPath)'
      arguments: '-c Release'
  - script: |
      az containerapp up \
      -n $(caName) -g $(rg) \
      --environment $(acaEnv) \
      --source $(projectPath) \
      --registry-server '$(registry).azurecr.io'
