trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  projectPath: src/Catalog.API
  caName: catalog-test
  rg: testapp-rg
  acaEnv: testappenv12
  registry: eshoptestacr1

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Azure Learning Sub(d7e3c15f-a785-4ecd-944b-d03698d68b5d)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        docker build -t $(registry).azurecr.io/catalog.api:latest --build-arg SERVICE=Catalog.API -f Dockerfile .
        docker push $(registry).azurecr.io/catalog.api:latest

        az containerapp up \
        -n $(caName) -g $(rg) \
        --environment $(acaEnv) \
        --image $(registry).azurecr.io/catalog.api:latest \
        --registry-server '$(registry).azurecr.io'