trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureContainerApps@1
    inputs:
      appSourcePath: '$(System.DefaultWorkingDirectory)/src/Catalog.API'
      azureSubscription: 'Azure Learning Sub(d7e3c15f-a785-4ecd-944b-d03698d68b5d)'
      acrName: 'eshoptestacr1'
      containerAppName: 'catalogapi-test'
      resourceGroup: 'testapp-rg'
      containerAppEnvironment: 'testappenv12'
      environmentVariables: 'ConnectionStrings__catalogdb=secretref:dbconnection-catalogapi'
